### ISSUE TITLE
Audit private key material zeroing to ensure no copies stay in memory

### ISSUE THREAD

**Issue by aakselrod** [bottlepay/lndsigner#20]
@joostjager makes a good point at https://github.com/bottlepay/lndsigner/pull/11#discussion_r1093111183 that private key material may remain in memory despite our best efforts at erasing it. We should try to see if we can find if any copies are left after our zeroing, and figure out how to eliminate them. If we do find copies, the fixes may involve raising issues or offering patches upstream to vault.

**Comment by joostjager** [comment]
Is there an easy way to get a memory dump of all memory of the golang process, to grep on?

**Comment by aakselrod** [comment]
It looks like there's a `gcore` utility that comes with `gdb` that can be used to extract a core dump of a running process as it runs. I'll play with it a bit and see what I can find.

**Comment by aakselrod** [comment]
Duplicate of https://github.com/NYDIG/lndsigner/issues/17
