### ISSUE TITLE
Implement structured logging

### ISSUE THREAD

**Issue by aakselrod** [bottlepay/lndsigner#5]
In moving from `btclog` to `zap.Logger`, we have gained the ability to use structured logging. Some of the logs we're generating now could benefit from this improvement while others make more sense to be left the way they are. We should go through the places where we generate logs and update those that make sense to use structured logging.

**Comment by yimikao** [comment]
@aakselrod can i pick this up

**Comment by aakselrod** [comment]
@yimikao Sorry, posted from the wrong account. Yes, you can pick this up, I'll be glad to review/merge. Thank you!

**Comment by aakselrod** [comment]
Duplicate of https://github.com/NYDIG/lndsigner/issues/11
